/*******************************************************//**

@class		CWObjectTest

@brief		Tests for CW Core Object Class

	This class implements a generic object, a la JavaScript,
	with dynamic members (fields).  CWObject instances are
	nestable.

@author		Glyn Anderson	(LiquidHub.GHA)

@version	2015-02-03	LiquidHub.GHA
	Created.

@see		CWObject

	(c)2015 LiquidHub.  All Rights Reserved.  Unauthorized use is prohibited.

	This is a component of CW Core (tm), LiquidHub's middleware library for Salesforce.

***********************************************************/

@isTest
private class CWObjectTest
{
	static testMethod void myUnitTest()
	{
		//	@todo: implement unit test
	}
}